import type { CollectionRecord } from "./types";

const DAY = "2026-09-20";

function collection(
  slug: string,
  title: string,
  h1: string,
  description: string,
  intent: string,
  summary: string,
  pick: { gameId: string; reason: string },
  games: string[],
  guides: string[],
  related: string[],
  sections: CollectionRecord["sections"],
  faqs: CollectionRecord["faqs"],
): CollectionRecord {
  return {
    id: `collection:${slug}`,
    kind: "collection",
    path: `/collections/${slug}`,
    slug,
    title,
    description,
    h1,
    intent,
    summary,
    sections,
    faqs,
    relatedGameIds: games,
    relatedGuideIds: guides,
    relatedCollectionIds: related,
    publishedAt: DAY,
    updatedAt: DAY,
    indexable: true,
    image: `/art/${games[0]}-hero.svg`,
    pick,
  };
}

export const COLLECTIONS: CollectionRecord[] = [
  collection(
    "quick-games",
    "Quick Browser Games for Short Sessions | Gamesweb",
    "Quick browser games",
    "Five Gamesweb titles that resolve in under two minutes: Sky Stack, Pocket Striker, Knockout Circuit, Crowd Control, and Velocity Run.",
    "Find a short session that still has a real loop.",
    "If you have one commute or a coffee, these five finish a run before the tab gets stale.",
    { gameId: "sky-stack", reason: "A climb can end in 20 seconds. Fever streaks still reward a second try." },
    ["sky-stack", "pocket-striker", "knockout-circuit", "crowd-control", "velocity-run"],
    ["guide:sky-stack:perfect-placement", "guide:pocket-striker:aiming", "guide:crowd-control:gates"],
    ["score-attack-games", "precision-games", "time-attack-games"],
    [
      {
        heading: "What “quick” means here",
        body: "Session hints in the catalog are measured, not marketing. Sky Stack targets 20–90 seconds. Pocket Striker and Velocity Run sit in the 30–90 window. Crowd Control finishes in 45–75. Knockout Circuit can stretch to two minutes if you take expert lines, but Starter Gates is still a short heat.",
      },
      {
        heading: "Which one should I play?",
        body: "Want one input? Sky Stack. Want aiming? Pocket Striker. Want a race against a ghost? Velocity Run or Knockout Circuit. Want a decision every few seconds? Crowd Control gates.",
      },
      {
        heading: "How they differ",
        body: "Sky Stack is vertical and zen. Pocket is a table. Velocity is rooftop time-attack. Knockout is a toy game-show. Crowd is a festival runner. They share a short clock, not a look.",
      },
    ],
    [
      { q: "Do these games save mid-run?", a: "No. A death or miss closes the attempt. Retry is instant so a short session stays honest." },
      { q: "Can I play them on a phone?", a: "Yes. All five accept touch. Sky Stack and Crowd Control are built for one thumb." },
    ],
  ),
  collection(
    "skill-games",
    "Skill Browser Games on Gamesweb",
    "Skill games",
    "Neon Drift, Velocity Run, Pocket Striker, and Sky Stack ask for a line, a jump, an aim, or a perfect overlap — not a grind.",
    "Pick a game where the player, not a loadout, decides the score.",
    "Four titles where a cleaner input is immediately visible on the next run.",
    { gameId: "neon-drift", reason: "The banked score only grows if you hold a real slide. Straightening dumps the combo." },
    ["neon-drift", "velocity-run", "pocket-striker", "sky-stack"],
    ["guide:neon-drift:how-to-drift", "guide:velocity-run:jump-timing", "guide:pocket-striker:aiming"],
    ["precision-games", "score-attack-games", "time-attack-games"],
    [
      {
        heading: "The skill is on the stick",
        body: "Neon Drift scores the slide, not the lap time. Velocity Run prints split deltas against your ghost and throws the attempt away on death. Pocket Striker counts strokes. Sky Stack shrinks the slab when you miss the overlap.",
      },
      {
        heading: "Which one should I play?",
        body: "If you like cars, start on Harbour and hold the first corner. If you like parkour, Gate A teaches coyote time in thirty seconds. If you want a quieter skill, Pocket’s Garden tables or Sky Stack’s first ten floors.",
      },
      {
        heading: "What is not a skill tax",
        body: "None of these hide a paywall or a long unlock tree. Modes are tracks, courses, tables, or a climb — you pick them from the hub.",
      },
    ],
    [{ q: "Is Swarm a skill game?", a: "It is, but the skill is positioning and builds over six minutes. It lives with survival, not this short-skill set." }],
  ),
  collection(
    "arcade-games",
    "Arcade Browser Games — Toy, Table, Stack, Crowd | Gamesweb",
    "Arcade games",
    "Knockout Circuit, Sky Stack, Crowd Control, and Pocket Striker are the bright, immediate arcade side of Gamesweb.",
    "Find the loud, readable arcade loop.",
    "Four games that photograph as toys or tables, not as a dark neon prototype.",
    { gameId: "knockout-circuit", reason: "Foam arms and a finish banner read in half a second. Ghosts turn a solo heat into a race." },
    ["knockout-circuit", "sky-stack", "crowd-control", "pocket-striker"],
    ["guide:knockout-circuit:obstacles", "guide:crowd-control:gates", "guide:sky-stack:streaks"],
    ["quick-games", "score-attack-games", "ghost-race-games"],
    [
      {
        heading: "Arcade, not a dark tech demo",
        body: "Knockout is a toy industrial game-show. Sky Stack is ceramic slabs against a changing sky. Crowd Control is a festival boulevard with huge +N / ×N signs. Pocket Striker is a felt table with a lamp and a score plaque.",
      },
      {
        heading: "Which one should I play?",
        body: "Want moving hazards? Knockout. Want one tap? Sky Stack. Want left-or-right math? Crowd Control. Want a bank shot? Pocket Striker.",
      },
    ],
    [{ q: "Is Neon Drift arcade?", a: "It is an arcade drift, but the world is midnight touge. It sits with score-attack and skill, not this bright set." }],
  ),
  collection(
    "score-attack-games",
    "Score-Attack Browser Games | Gamesweb",
    "Score-attack games",
    "Neon Drift, Swarm Protocol, Territory Rush, Crowd Control, and Sky Stack all chase a higher number — each with a different risk.",
    "Compare how Gamesweb turns a run into a number.",
    "Five higher-is-better loops that do not share a scoring rule.",
    { gameId: "neon-drift", reason: "Live points are worthless until you bank them. That single rule is the whole sport." },
    ["neon-drift", "swarm-protocol", "territory-rush", "crowd-control", "sky-stack"],
    ["guide:neon-drift:live-vs-banked", "guide:swarm-protocol:high-score", "guide:territory-rush:percentage"],
    ["skill-games", "time-attack-games", "daily-challenge-games"],
    [
      {
        heading: "Five ways to make a number",
        body: "Neon banks drift combo. Swarm adds kills, time, and a Core bonus. Territory multiplies paint percentage, cuts, and largest capture. Crowd multiplies pack size at the finish. Sky Stack pays floors and perfect streaks.",
      },
      {
        heading: "Which one should I play?",
        body: "Two-minute score? Neon or Sky. Ninety seconds of space control? Territory. A longer build? Swarm. A runner that ends in a parade? Crowd.",
      },
    ],
    [{ q: "Why isn’t Velocity here?", a: "Velocity and Knockout and Pocket are lower-is-better. They live on the time-attack shelf." }],
  ),
  collection(
    "time-attack-games",
    "Time-Attack Browser Games | Gamesweb",
    "Time-attack games",
    "Velocity Run, Knockout Circuit, and Pocket Striker treat the clock or the stroke count as the sport.",
    "Find a run where faster or fewer is the win.",
    "Three titles that punish hesitation more than they punish a low score.",
    { gameId: "velocity-run", reason: "Medals are time gates. Death closes the attempt so the clock cannot be farmed." },
    ["velocity-run", "knockout-circuit", "pocket-striker"],
    ["guide:velocity-run:medals", "guide:knockout-circuit:timing", "guide:pocket-striker:scoring"],
    ["precision-games", "ghost-race-games", "quick-games"],
    [
      {
        heading: "Clock versus strokes",
        body: "Velocity and Knockout store milliseconds. Pocket stores strokes — a one-stroke ace beats a slow clean table. All three retry instantly. Velocity checkpoints print splits; they do not save you.",
      },
      {
        heading: "Ghosts",
        body: "Velocity and Knockout replay a recorded line as a runner. Pocket does not. If you want a visible rival on the course, pick a rooftop or a foam map.",
      },
    ],
    [{ q: "Do medals exist in Knockout?", a: "Knockout scores finish time. Velocity is the one with Bronze through Platinum medals on each course." }],
  ),
  collection(
    "competitive-browser-games",
    "Competitive Browser Games with Ghosts and Challenges | Gamesweb",
    "Competitive browser games",
    "Neon Drift, Velocity Run, Knockout Circuit, and Swarm Protocol support challenges, same-seed fights, and verified boards.",
    "Play against a score that someone actually posted.",
    "Four games built for async rivalry, not invented opponents.",
    { gameId: "velocity-run", reason: "Same course, same ghost tape, same medal table. A rematch is a split hunt." },
    ["neon-drift", "velocity-run", "knockout-circuit", "swarm-protocol"],
    ["guide:neon-drift:ghost-pb", "guide:velocity-run:ghost-runs", "guide:knockout-circuit:ghosts"],
    ["ghost-race-games", "daily-challenge-games", "score-attack-games"],
    [
      {
        heading: "What competition looks like",
        body: "Challenges copy a score and a seed. Ghosts in Neon, Velocity, and Knockout are recorded runs. Swarm uses survive-seed and beat-build, not a racing ghost. Territory and Crowd can be challenged too, but these four carry the densest rival tools.",
      },
      {
        heading: "Which one should I play?",
        body: "Race a line: Velocity or Knockout. Race a banked number: Neon. Race a build: Swarm on the same seed.",
      },
    ],
    [{ q: "Are leaderboard names fake?", a: "No. Empty boards stay empty. Friends boards wait for a real friend score." }],
  ),
  collection(
    "daily-challenge-games",
    "Daily Challenge Browser Games | Gamesweb",
    "Daily challenge games",
    "Every Gamesweb title can join Daily Arcade. This set explains which loops feel best as a shared daily.",
    "Pick today’s run from games that already have a daily mode.",
    "A daily is the same authored content for everyone that day — not an infinite archive of dates.",
    { gameId: "neon-drift", reason: "The daily drift target is a shared Harbour/District/Ridge seed, not a new track." },
    ["neon-drift", "velocity-run", "swarm-protocol", "sky-stack", "knockout-circuit", "pocket-striker", "territory-rush", "crowd-control"],
    ["guide:neon-drift:tracks", "guide:velocity-run:courses", "guide:sky-stack:high-stack"],
    ["score-attack-games", "quick-games", "competitive-browser-games"],
    [
      {
        heading: "What Daily Arcade actually is",
        body: "Daily Arcade is a three-step route for the day. Each game already exposes a daily mode in its hub. We do not generate dated archive pages. If you missed yesterday, you play today.",
      },
      {
        heading: "Which daily feels best",
        body: "Short and comparable: Sky Stack, Pocket, Neon, Velocity. Longer: Swarm. Space-control: Territory. Route-memory: Crowd Control.",
      },
    ],
    [{ q: "Can I replay yesterday’s daily?", a: "Not as an indexable archive. Play the current Daily Arcade or open the game hub and run a normal mode." }],
  ),
  collection(
    "precision-games",
    "Precision Browser Games | Gamesweb",
    "Precision games",
    "Velocity Run, Pocket Striker, Sky Stack, and Neon Drift reward a clean edge — coyote time, aim, overlap, or a near-miss curb.",
    "Find the game that punishes sloppy inputs.",
    "Four loops where a pixel or a degree of slip is the difference.",
    { gameId: "velocity-run", reason: "Coyote time and jump buffer are real. Fast ledges and expert skips are optional, not required." },
    ["velocity-run", "pocket-striker", "sky-stack", "neon-drift"],
    ["guide:velocity-run:coyote-time", "guide:pocket-striker:precision", "guide:sky-stack:perfect-placement"],
    ["skill-games", "time-attack-games", "quick-games"],
    [
      {
        heading: "Four kinds of precision",
        body: "Velocity: leave a ledge late and the coyote window still jumps. Pocket: power and angle, then a cushion. Sky: the slab must overlap. Neon: the inner curb is a near-miss bonus if you stay on asphalt.",
      },
      {
        heading: "Which one should I play?",
        body: "Platformer precision → Velocity. Table precision → Pocket. Timing precision → Sky. Vehicle precision → Neon.",
      },
    ],
    [{ q: "Does Knockout belong here?", a: "It is timing-heavy, but the spectacle is the obstacle, not a pixel-perfect medal table. It sits with arcade and time-attack." }],
  ),
  collection(
    "ghost-race-games",
    "Ghost Race Browser Games | Gamesweb",
    "Ghost race games",
    "Neon Drift, Velocity Run, Knockout Circuit, and Crowd Control replay a recorded run so a solo heat still has a rival.",
    "Race a tape, not a bot pretending to be a person.",
    "Four games where G or a finish writes a ghost you can beat later.",
    { gameId: "neon-drift", reason: "Toggle G. The ghost drives your last tape on Harbour, District, or Ridge." },
    ["neon-drift", "velocity-run", "knockout-circuit", "crowd-control"],
    ["guide:neon-drift:ghost-pb", "guide:velocity-run:ghost-runs", "guide:crowd-control:routes"],
    ["competitive-browser-games", "time-attack-games", "score-attack-games"],
    [
      {
        heading: "What a ghost is",
        body: "A ghost is a recorded sample tape. Velocity and Knockout draw another runner. Neon draws another car. Crowd remembers which lane the ghost took and shows a pale marker. None of them are live multiplayer.",
      },
      {
        heading: "Which one should I play?",
        body: "Want splits? Velocity. Want a foam race? Knockout. Want a banked number against a line? Neon. Want a route argument? Crowd.",
      },
    ],
    [{ q: "Why no Swarm ghost?", a: "Swarm is an arena build. Same-seed survival is the comparable tool, not a racing tape." }],
  ),
  collection(
    "survival-and-arena",
    "Survival and Arena Browser Games | Gamesweb",
    "Survival and arena games",
    "Swarm Protocol, Territory Rush, and Crowd Control put a body count or a paint percentage under pressure.",
    "Pick a game where the field fills up.",
    "Three loops that escalate: more hostiles, more paint, more people in the pack.",
    { gameId: "swarm-protocol", reason: "Opening is six silhouettes. Peak should feel like the build is carrying a crowded deck." },
    ["swarm-protocol", "territory-rush", "crowd-control"],
    ["guide:swarm-protocol:enemy-types", "guide:territory-rush:trail-risk", "guide:crowd-control:clash"],
    ["score-attack-games", "arcade-games", "daily-challenge-games"],
    [
      {
        heading: "Three kinds of pressure",
        body: "Swarm: skitterers, sporers, tanks, elites, then the Core. Territory: leave your color and the trail can be cut. Crowd: a −20 gate or a clash can empty the pack.",
      },
      {
        heading: "Which one should I play?",
        body: "Six to eight minutes → Swarm. Ninety seconds of paint → Territory. A one-thumb runner → Crowd.",
      },
    ],
    [{ q: "Are Territory opponents people?", a: "No. BRICK, NEEDLE, and SWEEP are labeled bots with deterministic paths." }],
  ),
  collection(
    "one-thumb-games",
    "One-Thumb Browser Games | Gamesweb",
    "One-thumb games",
    "Sky Stack, Crowd Control, and Pocket Striker can be played with a thumb: tap, steer, or drag.",
    "Play without a keyboard if you want to.",
    "Three titles that stay readable on a 390-wide phone.",
    { gameId: "sky-stack", reason: "One tap places the slab. The rest is the sky and the streak." },
    ["sky-stack", "crowd-control", "pocket-striker"],
    ["guide:sky-stack:timing", "guide:crowd-control:preservation", "guide:pocket-striker:aiming"],
    ["quick-games", "arcade-games", "precision-games"],
    [
      {
        heading: "Thumb, not a virtual stick farm",
        body: "Sky Stack is tap-to-place. Crowd Control steers a pack that already runs forward. Pocket Striker is drag-to-aim. Neon and Velocity also accept touch, but they want two zones.",
      },
      {
        heading: "Which one should I play?",
        body: "Standing in a queue → Sky Stack. Want decisions → Crowd. Want a table → Pocket.",
      },
    ],
    [{ q: "Is Knockout one-thumb?", a: "It has a jump and a dash. Playable on touch, but it is not a one-button game." }],
  ),
];
