import type { SeoEntry } from "./types";

const DAY = "2026-09-20";

function learn(
  slug: string,
  title: string,
  h1: string,
  description: string,
  intent: string,
  summary: string,
  games: string[],
  collections: string[],
  guides: string[],
  sections: SeoEntry["sections"],
  faqs?: SeoEntry["faqs"],
): SeoEntry {
  return {
    id: `learn:${slug}`,
    kind: "learn",
    path: `/learn/${slug}`,
    slug,
    title,
    description,
    h1,
    intent,
    summary,
    sections,
    faqs,
    relatedGameIds: games,
    relatedGuideIds: guides,
    relatedCollectionIds: collections,
    publishedAt: DAY,
    updatedAt: DAY,
    indexable: true,
    image: `/art/${games[0]}-hero.svg`,
  };
}

export const LEARN_PAGES: SeoEntry[] = [
  learn(
    "browser-games",
    "What Browser Games Are on Gamesweb",
    "Browser games, as we ship them",
    "Gamesweb browser games load in the tab, keep one player identity, and retry without a store page.",
    "Understand what this catalog actually is.",
    "Eight authored loops. No download. No invented social graph.",
    ["neon-drift", "velocity-run", "swarm-protocol"],
    ["quick-games", "daily-challenge-games"],
    ["guide:neon-drift:how-to-drift", "guide:velocity-run:beginner-movement"],
    [
      {
        heading: "The loop",
        body: "You open a Game Hub, press Play, and the canvas boots a Phaser or canvas world. A run ends with a result: banked score, finish time, survival score, strokes, paint percent, floors, or pack size. Retry is R or the chamfered Play again.",
      },
      {
        heading: "What makes it hard",
        body: "Each title has one expensive decision. Neon: when to bank. Velocity: when to jump. Swarm: which upgrade. Knockout: which route. Pocket: power. Territory: when to leave paint. Sky: when to tap. Crowd: which gate.",
      },
      {
        heading: "How to choose",
        body: "Short clock → Sky, Pocket, Crowd. Race → Velocity or Knockout. Number that grows → Neon, Territory, Swarm. All eight are on /games.",
      },
    ],
    [{ q: "Do I need an account?", a: "A guest can play. Saving a profile keeps PB, trophies, and friends. Play pages stay noindex either way." }],
  ),
  learn(
    "arcade-games",
    "What an Arcade Game Means on Gamesweb",
    "Arcade, as we ship it",
    "On Gamesweb, arcade means a readable toy loop: Knockout foam, Sky slabs, Crowd gates, Pocket felt.",
    "Separate arcade spectacle from score-attack night roads.",
    "Bright materials, obvious hazards, instant retry.",
    ["knockout-circuit", "sky-stack", "crowd-control", "pocket-striker"],
    ["arcade-games", "quick-games"],
    ["guide:knockout-circuit:obstacles", "guide:crowd-control:gates"],
    [
      { heading: "The loop", body: "See the obstacle or the gate, act, watch the payoff, retry. Arcade here is about silhouette size, not a quarter cabinet." },
      { heading: "What makes it hard", body: "Knockout arms and crushers. Crowd minus gates. Sky shrinking width. Pocket cushions that dump a long aim." },
      { heading: "How to choose", body: "Moving hazards → Knockout. Math gates → Crowd. One tap → Sky. Aim → Pocket." },
    ],
  ),
  learn(
    "drift-games",
    "How Drift Games Work — Neon Drift",
    "Drift games",
    "Neon Drift is Gamesweb’s drift title: hold the slide, grow LIVE, bank before you straighten.",
    "Learn the only drift loop we actually ship.",
    "If the combo dies when you grip up, you are playing Neon, not a sim.",
    ["neon-drift"],
    ["score-attack-games", "skill-games"],
    ["guide:neon-drift:how-to-drift", "guide:neon-drift:live-vs-banked", "guide:neon-drift:combo"],
    [
      { heading: "The loop", body: "Accelerate into a corner, hold the slide, skim the apex, chain sectors, then straighten to bank. Two laps finish Harbour, District, or Ridge." },
      { heading: "What makes it hard", body: "LIVE is not BANKED. A wall hit or a straight line dumps the combo. Near-miss curb pays extra if you stay on asphalt." },
      { heading: "How to choose", body: "We have one drift game. Tracks change the roadside — mountain touge, service industrial, tunnel urban — not the scoring rule." },
    ],
    [{ q: "Is there a grip assist?", a: "Touch gets a steer assist. Keyboard is raw. Space is handbrake. 1/2/3 switch tracks." }],
  ),
  learn(
    "parkour-games",
    "How Parkour Games Work — Velocity Run",
    "Parkour games",
    "Velocity Run is rooftop parkour with coyote time, jump buffer, and medals. Death closes the attempt.",
    "Learn the only parkour course family we ship.",
    "Three course kits: HVAC roofs, construction/transit, communications tower.",
    ["velocity-run", "knockout-circuit"],
    ["time-attack-games", "precision-games"],
    ["guide:velocity-run:coyote-time", "guide:velocity-run:medals", "guide:velocity-run:courses"],
    [
      { heading: "The loop", body: "Run right, jump, fast-fall, take safe/fast/expert ledges, hit the beacon. Checkpoints print splits against your ghost. They do not save you." },
      { heading: "What makes it hard", body: "Milliseconds are the sport. Platinum is a clean ghost. Fast-fall (S/↓) is a real input, not decoration." },
      { heading: "How to choose", body: "Want rooftops and medals → Velocity. Want foam arms and a banner → Knockout. They do not share a sky family anymore." },
    ],
  ),
  learn(
    "survivor-games",
    "How Survivor Games Work — Swarm Protocol",
    "Survivor games",
    "Swarm Protocol is an arena survivor: auto-fire, dash i-frames, upgrades, elites, then the Core.",
    "Learn the only survivor we ship, including what the enemies actually are.",
    "Skitterer, swarmer, spore, shell tank, elite, Core — not one recolored circle.",
    ["swarm-protocol"],
    ["survival-and-arena", "score-attack-games"],
    ["guide:swarm-protocol:beginner-survival", "guide:swarm-protocol:upgrades", "guide:swarm-protocol:core-boss"],
    [
      { heading: "The loop", body: "Move. The gun tracks. Cores level you. Pick one of three upgrades. Dash through telegraphs. Kill the Core or continue Endless after the result." },
      { heading: "What makes it hard", body: "Builds rewrite minute six. Same-seed challenges compare those builds. FPS stay inside the existing quality tier." },
      { heading: "How to choose", body: "If you want a 90-second arena instead, that is Territory Rush. Swarm is the 6–8 minute one." },
    ],
  ),
  learn(
    "score-attack-games",
    "How Score-Attack Works on Gamesweb",
    "Score-attack",
    "Higher is better on Neon, Swarm, Territory, Crowd, and Sky — but the number is made differently in each.",
    "Stop treating every high score as the same sport.",
    "Banked drift ≠ paint % ≠ pack × finish multiplier ≠ floors.",
    ["neon-drift", "swarm-protocol", "territory-rush", "crowd-control", "sky-stack"],
    ["score-attack-games"],
    ["guide:neon-drift:scoring", "guide:territory-rush:how-territory-works", "guide:crowd-control:multipliers"],
    [
      { heading: "The loop", body: "A run produces one comparable number. Neon refuses to count unbanked LIVE. Territory pays percent × 400 plus cuts. Crowd waits for the finish multiplier." },
      { heading: "What makes it hard", body: "The expensive moment is always a risk: straighten, leave paint, take a minus gate, miss a slab, greed a Core fight." },
      { heading: "How to choose", body: "Read the collection page if you want a picker. This page is the rule difference." },
    ],
  ),
  learn(
    "time-attack-games",
    "How Time-Attack Works on Gamesweb",
    "Time-attack",
    "Velocity Run and Knockout Circuit store milliseconds. Pocket Striker stores strokes. Death or a twelfth stroke closes the table.",
    "Learn why faster or fewer is the win.",
    "Lower is better. Ghosts optional. Medals are Velocity-only.",
    ["velocity-run", "knockout-circuit", "pocket-striker"],
    ["time-attack-games"],
    ["guide:velocity-run:speedrun-basics", "guide:knockout-circuit:timing", "guide:pocket-striker:scoring"],
    [
      { heading: "The loop", body: "Start, commit, finish or die. Velocity medals sit on each course. Knockout just wants the banner. Pocket wants par or an ace." },
      { heading: "What makes it hard", body: "Hesitation. Velocity will not checkpoint-save you. Pocket will sink you after 12 slow strokes." },
      { heading: "How to choose", body: "Rooftops → Velocity. Toy show → Knockout. Table → Pocket." },
    ],
  ),
  learn(
    "territory-games",
    "How Territory Games Work — Territory Rush",
    "Territory games",
    "Territory Rush is a 90-second paint loop: leave owned ground, trail, close, fill, watch the percent.",
    "Learn the only territory game we ship.",
    "Paint is the sport. Toy houses are context.",
    ["territory-rush"],
    ["survival-and-arena", "score-attack-games"],
    ["guide:territory-rush:how-territory-works", "guide:territory-rush:trail-risk", "guide:territory-rush:large-vs-small"],
    [
      { heading: "The loop", body: "Move off your color. The ribbon is a claim in progress. Return to your color to flood-fill the interior. A self-cross ends the run. Cutting BRICK, NEEDLE, or SWEEP scores an elimination." },
      { heading: "What makes it hard", body: "A long trail is a bigger fill and a bigger target. Bots can cut you. Blocked toy buildings are collision, not paint." },
      { heading: "How to choose", body: "Toy City versus Plaza changes the blocked rectangles, not the rule." },
    ],
  ),
  learn(
    "stacking-games",
    "How Stacking Games Work — Sky Stack",
    "Stacking games",
    "Sky Stack is one tap, a moving slab, leftover width, and a fever streak against a dawn-to-dusk sky.",
    "Learn the only stacker we ship.",
    "Zen until the slab is thinner than your nerve.",
    ["sky-stack"],
    ["one-thumb-games", "quick-games"],
    ["guide:sky-stack:perfect-placement", "guide:sky-stack:streaks", "guide:sky-stack:high-stack"],
    [
      { heading: "The loop", body: "A slab travels. Tap. Perfect overlap keeps width and feeds fever. A miss ends the climb. Floor 30 and floor 67 are trophy marks." },
      { heading: "What makes it hard", body: "Width shrinks. Speed stays readable. The sky shifts dawn → day → gold → lavender so height is a place, not a black void." },
      { heading: "How to choose", body: "If you wanted physics banks, that is Pocket. Sky is one button." },
    ],
  ),
  learn(
    "crowd-runner-games",
    "How Crowd Runners Work — Crowd Control",
    "Crowd runners",
    "Crowd Control steers a pack into +N, ×N, −N, and ÷N gates, then cashes a finish multiplier.",
    "Learn the only crowd runner we ship.",
    "If the screenshot does not show a huge +30, the gate is too small — we fixed that.",
    ["crowd-control"],
    ["arcade-games", "one-thumb-games"],
    ["guide:crowd-control:gates", "guide:crowd-control:multipliers", "guide:crowd-control:clash"],
    [
      { heading: "The loop", body: "Forward is automatic. Steer left or right. Touch a gate to apply add/mul/sub/div. Clash or a 0 pack ends the run. Finish banners 12 / 24 / 48 / 96." },
      { heading: "What makes it hard", body: "A ×2 on 40 is not the same as +8. Shortcuts raise speed. Guardians appear on boss routes." },
      { heading: "How to choose", body: "If you wanted parkour precision, play Velocity. Crowd is a count." },
    ],
  ),
  learn(
    "one-button-games",
    "One-Button Games — Sky Stack",
    "One-button games",
    "Sky Stack is the one-button title: Space, click, or tap places the slab. Crowd and Pocket need a steer or a drag.",
    "Know which Gamesweb title is truly one button.",
    "Do not call every mobile game one-button.",
    ["sky-stack"],
    ["one-thumb-games", "quick-games"],
    ["guide:sky-stack:timing"],
    [
      { heading: "The loop", body: "One input. The rest is timing. R retries." },
      { heading: "What makes it hard", body: "The moving piece does not wait. Fever multiplies only while you stay perfect." },
      { heading: "How to choose", body: "Need a second input? That is not this page." },
    ],
  ),
  learn(
    "short-session-games",
    "Short-Session Browser Games",
    "Short sessions",
    "Most Gamesweb loops fit in a break. Swarm is the exception at 6–8 minutes.",
    "Pick a run that matches the time you have.",
    "Measured sessionHint values, not “hours of fun.”",
    ["sky-stack", "pocket-striker", "velocity-run", "crowd-control", "neon-drift"],
    ["quick-games"],
    ["guide:sky-stack:timing", "guide:neon-drift:beginner-mistakes"],
    [
      { heading: "The loop", body: "Boot, play, result, retry. Session ranges live on each Game Hub." },
      { heading: "What makes it hard", body: "A short clock still has a real fail state. Pocket sinks you at 12 strokes. Velocity voids the run on death." },
      { heading: "How to choose", body: "Under a minute → Sky. About a minute → Pocket, Velocity, Crowd, Neon. A coffee → Swarm." },
    ],
  ),
];
