import { brand } from "@gamesweb/config";
import type { SeoEntry } from "./types";

const DAY = "2026-09-20";

export const STATIC_PAGES: SeoEntry[] = [
  {
    id: "home",
    kind: "home",
    path: "/",
    slug: "home",
    title: `${brand.productName} — ${brand.tagline}`,
    description: brand.description,
    h1: brand.productName,
    intent: "Launch into a game.",
    summary: "Premium launcher. Not the SEO catalog.",
    sections: [{ heading: "Play", body: "Focus a title and press Play. The public catalog lives at /games." }],
    relatedGameIds: ["neon-drift", "velocity-run", "swarm-protocol"],
    relatedGuideIds: ["guide-hub:neon-drift"],
    relatedCollectionIds: ["quick-games"],
    publishedAt: "2026-09-14",
    updatedAt: DAY,
    indexable: true,
    image: "/art/neon-drift-hero.svg",
  },
  {
    id: "catalog",
    kind: "catalog",
    path: "/games",
    slug: "games",
    title: "Free Browser Games — Gamesweb Catalog",
    description: "Eight authored browser games. Genre, session length, input, and crawlable hubs. Arcade stays the personal launcher.",
    h1: "Games",
    intent: "Browse the public catalog.",
    summary: "Eight authored browser games. Pick a title, then play it in the tab.",
    sections: [
      { heading: "Why play in the browser", body: "Each title boots in the tab, retries with R, and stores a real PB on your identity. No store page. No invented reviews." },
      { heading: "How to choose", body: "Use collections if you know the mood. Use guides if you already picked a title. Use this page if you want the eight cards." },
    ],
    relatedGameIds: ["neon-drift", "velocity-run", "swarm-protocol", "knockout-circuit", "pocket-striker", "territory-rush", "sky-stack", "crowd-control"],
    relatedGuideIds: ["guide-hub:neon-drift", "guide-hub:velocity-run"],
    relatedCollectionIds: ["quick-games", "score-attack-games", "arcade-games"],
    publishedAt: DAY,
    updatedAt: DAY,
    indexable: true,
    image: "/art/neon-drift-hero.svg",
  },
  {
    id: "collection-index",
    kind: "collection-index",
    path: "/collections",
    slug: "collections",
    title: "Game Collections | Gamesweb",
    description: "Curated Gamesweb collections: quick, skill, arcade, score-attack, time-attack, and more. Each set has at least three real titles.",
    h1: "Collections",
    intent: "Pick a mood, then a game.",
    summary: "Curated, not doorways.",
    sections: [{ heading: "How these are built", body: "A collection needs three relevant games and a reason that would be false on another set." }],
    relatedGameIds: ["neon-drift", "sky-stack", "crowd-control"],
    relatedGuideIds: ["guide-hub:neon-drift", "guide-hub:knockout-circuit"],
    relatedCollectionIds: [
      "quick-games",
      "skill-games",
      "arcade-games",
      "score-attack-games",
      "time-attack-games",
      "competitive-browser-games",
      "daily-challenge-games",
      "precision-games",
      "ghost-race-games",
      "survival-and-arena",
      "one-thumb-games",
    ],
    publishedAt: DAY,
    updatedAt: DAY,
    indexable: true,
  },
  {
    id: "guide-index",
    kind: "guide-index",
    path: "/guides",
    slug: "guides",
    title: "Game Guides | Gamesweb",
    description: "Guides for all eight Gamesweb titles. Written from the shipped mechanics — scoring, tracks, gates, dashes — not generic browser-game filler.",
    h1: "Guides",
    intent: "Find a guide hub, then a deep page.",
    summary: "Specific to the build.",
    sections: [{ heading: "How to read them", body: "Start at a game hub. Deep guides do not invent systems that are not in the code." }],
    relatedGameIds: ["neon-drift", "velocity-run", "swarm-protocol"],
    relatedGuideIds: [
      "guide-hub:neon-drift",
      "guide-hub:velocity-run",
      "guide-hub:swarm-protocol",
      "guide-hub:knockout-circuit",
      "guide-hub:pocket-striker",
      "guide-hub:territory-rush",
      "guide-hub:sky-stack",
      "guide-hub:crowd-control",
    ],
    relatedCollectionIds: ["skill-games"],
    publishedAt: DAY,
    updatedAt: DAY,
    indexable: true,
  },
  {
    id: "learn-index",
    kind: "learn-index",
    path: "/learn",
    slug: "learn",
    title: "Learn Browser Game Types | Gamesweb",
    description: "Short explainers for drift, parkour, survivor, territory, stacking, and crowd-runner loops — tied to games you can play here.",
    h1: "Learn",
    intent: "Understand a type, then play an example.",
    summary: "Editorial, not a 1,000-word CTA.",
    sections: [{ heading: "What belongs here", body: "A learn page exists only when Gamesweb has a playable example and a real loop to describe." }],
    relatedGameIds: ["neon-drift", "sky-stack"],
    relatedGuideIds: ["guide-hub:neon-drift"],
    relatedCollectionIds: ["quick-games"],
    relatedLearnIds: [
      "learn:browser-games",
      "learn:arcade-games",
      "learn:drift-games",
      "learn:parkour-games",
      "learn:survivor-games",
      "learn:score-attack-games",
      "learn:time-attack-games",
      "learn:territory-games",
      "learn:stacking-games",
      "learn:crowd-runner-games",
      "learn:one-button-games",
      "learn:short-session-games",
    ],
    publishedAt: DAY,
    updatedAt: DAY,
    indexable: true,
  },
  {
    id: "about",
    kind: "legal",
    path: "/about",
    slug: "about",
    title: "About Gamesweb",
    description: `${brand.productName} is a browser arcade with one player identity across instant games.`,
    h1: "About",
    intent: "Who ships this.",
    summary: "Product, not a blog.",
    sections: [{ heading: "About", body: brand.description }],
    relatedGameIds: ["neon-drift"],
    relatedGuideIds: [],
    relatedCollectionIds: [],
    publishedAt: "2026-09-14",
    updatedAt: DAY,
    indexable: true,
  },
  {
    id: "privacy",
    kind: "legal",
    path: "/privacy",
    slug: "privacy",
    title: "Privacy | Gamesweb",
    description: "How Gamesweb handles player data and optional analytics.",
    h1: "Privacy",
    intent: "Policy.",
    summary: "Legal.",
    sections: [{ heading: "Privacy", body: "See the privacy page for the full policy." }],
    relatedGameIds: [],
    relatedGuideIds: [],
    relatedCollectionIds: [],
    publishedAt: "2026-09-14",
    updatedAt: DAY,
    indexable: true,
  },
  {
    id: "terms",
    kind: "legal",
    path: "/terms",
    slug: "terms",
    title: "Terms | Gamesweb",
    description: "Terms of use for Gamesweb.",
    h1: "Terms",
    intent: "Policy.",
    summary: "Legal.",
    sections: [{ heading: "Terms", body: "See the terms page for the full policy." }],
    relatedGameIds: [],
    relatedGuideIds: [],
    relatedCollectionIds: [],
    publishedAt: "2026-09-14",
    updatedAt: DAY,
    indexable: true,
  },
];
