import type { AchievementDefinition, ChallengeType, GameManifest, SocialMode } from "./types";

const DEVICES: GameManifest["supportedDevices"] = ["desktop", "laptop", "tablet", "mobile"];
const SOCIAL: SocialMode[] = ["solo", "async-duel", "ghost-race", "party", "daily"];
const SCORE_CHALLENGE: ChallengeType[] = ["beat-score", "same-seed"];
const TIME_CHALLENGE: ChallengeType[] = ["beat-time", "beat-ghost", "same-seed"];

const platformAchievements: AchievementDefinition[] = [
  { key: "first-run", name: "First Run", description: "Finish any game once.", xp: 20 },
  { key: "three-worlds", name: "Three Worlds", description: "Play the three original launch games.", xp: 80 },
  { key: "arcade-tourist", name: "Arcade Tourist", description: "Play 5 different games.", xp: 70 },
  { key: "world-tour", name: "World Tour", description: "Play all 8 arcade games.", xp: 120 },
  { key: "on-fire", name: "On Fire", description: "Beat a personal record three times.", xp: 60 },
  { key: "night-shift", name: "Night Shift", description: "Play after midnight.", xp: 25 },
  { key: "explorer", name: "Explorer", description: "Play two genres in one session.", xp: 40 },
  { key: "return-tomorrow", name: "Return Tomorrow", description: "Keep a 2-day streak.", xp: 35 },
  { key: "weekender", name: "Weekender", description: "Reach a 7-day streak.", xp: 90 },
  { key: "social-spark", name: "Social Spark", description: "Copy an invite link.", xp: 15 },
  { key: "rivalry", name: "Rivalry", description: "Rematch the same player five times.", xp: 50 },
  { key: "untouchable", name: "Untouchable", description: "Win 5 challenges.", xp: 60 },
  { key: "social-butterfly", name: "Social Butterfly", description: "Challenge 10 unique players.", xp: 55 },
  { key: "daily-grinder", name: "Daily Grinder", description: "Complete a 7-day Daily Arcade streak.", xp: 80 },
  { key: "all-rounder", name: "All-Rounder", description: "Set a PB in 5 games.", xp: 70 },
  { key: "grand-prix-winner", name: "Grand Prix Winner", description: "Win an Arcade Grand Prix.", xp: 90 },
  { key: "crew-player", name: "Crew Player", description: "Contribute to a crew weekly challenge.", xp: 40 },
];

export const neonDriftManifest: GameManifest = {
  id: "neon-drift",
  slug: "neon-drift",
  title: "Neon Drift",
  tagline: "Hold the slide. Bank the score.",
  description:
    "Arcade drift score-attack. Keep the angle, skim the apex, and cash the combo before the grip comes back.",
  genre: "Driving",
  tags: ["drift", "score-attack", "arcade", "solo", "skill", "daily"],
  skills: ["timing", "line", "combo"],
  accent: "#e35aa0",
  accentSoft: "#3a1428",
  orientation: "landscape",
  inputMethods: ["keyboard", "touch"],
  thumbnail: "/art/neon-drift-card.svg",
  hero: "/art/neon-drift-hero.svg",
  heroImage: "/art/neon-drift-hero.svg",
  tileImage: "/art/neon-drift-card.svg",
  backdropImage: "/art/neon-drift-hero.svg",
  media: {
    backdrop: "/art/neon-drift-hero.svg",
    tile: "/art/neon-drift-card.svg",
    hero: "/art/neon-drift-hero.svg",
  },
  version: "1.2.0",
  supportedDevices: DEVICES,
  minPlayers: 1,
  maxPlayers: 4,
  sessionHint: "60–90 sec runs",
  sessionDuration: { minSec: 60, maxSec: 90 },
  modes: ["foundation", "technical", "velocity", "daily"],
  scoreDirection: "higher",
  socialModes: SOCIAL,
  challengeTypes: ["beat-score", "beat-ghost", "same-seed"],
  ghostSupport: true,
  dailySupport: true,
  partySupport: true,
  leaderboards: ["global", "friends", "rivals"],
  howToPlay: [
    "Accelerate into the first corner and hold a slide.",
    "Steer into the drift, then countersteer to keep the angle alive.",
    "Near-miss the inner curb and chain sectors to beat your ghost.",
    "Two laps finish the circuit. R retries instantly. 1/2/3 switch tracks.",
  ],
  controls: [
    { input: "W / ↑", action: "Accelerate" },
    { input: "S / ↓", action: "Brake" },
    { input: "A D / ← →", action: "Steer" },
    { input: "Space", action: "Handbrake" },
    { input: "1 2 3", action: "Switch track" },
    { input: "G", action: "Toggle ghost" },
    { input: "R", action: "Restart" },
  ],
  faq: [
    { q: "Why did my combo drop?", a: "The combo fades when you straighten out or drop below drift speed." },
    { q: "Is this a simulator?", a: "No. It is an arcade slide with weight, grip transitions, and a retry loop." },
  ],
  achievements: [
    { key: "first-slide", name: "First Slide", description: "Enter a drift.", xp: 15 },
    { key: "combo-5", name: "Heat 5", description: "Reach a 5x combo.", xp: 25 },
    { key: "score-25k", name: "Pink Line", description: "Score 25,000 in one run.", xp: 30 },
    { key: "score-60k", name: "Night Apex", description: "Score 60,000 in one run.", xp: 50 },
    { key: "two-laps", name: "Clean Circuit", description: "Finish two laps.", xp: 25 },
    { key: "near-miss", name: "Paint Swap", description: "Bank a near-miss bonus.", xp: 20 },
    { key: "grass-survive", name: "Dirt Warning", description: "Rejoin asphalt after grass.", xp: 15 },
    { key: "boost-gate", name: "Gatekeeper", description: "Hit a boost ribbon.", xp: 15 },
    { key: "no-crash-lap", name: "Quiet Hands", description: "Complete a lap without a wall hit.", xp: 35 },
    { key: "daily-drift", name: "Evening Line", description: "Finish the daily drift target.", xp: 30 },
  ],
};

export const velocityRunManifest: GameManifest = {
  id: "velocity-run",
  slug: "velocity-run",
  title: "Velocity Run",
  tagline: "Milliseconds are the sport.",
  description:
    "Precision parkour. Three short courses, coyote time, jump buffering, and a restart that never argues.",
  genre: "Platformer",
  tags: ["parkour", "time-attack", "precision", "solo", "skill", "competitive"],
  skills: ["jump", "routing", "splits"],
  accent: "#3ec6e8",
  accentSoft: "#0c2430",
  orientation: "landscape",
  inputMethods: ["keyboard", "touch"],
  thumbnail: "/art/velocity-run-card.svg",
  hero: "/art/velocity-run-hero.svg",
  heroImage: "/art/velocity-run-hero.svg",
  tileImage: "/art/velocity-run-card.svg",
  backdropImage: "/art/velocity-run-hero.svg",
  media: {
    backdrop: "/art/velocity-run-hero.svg",
    tile: "/art/velocity-run-card.svg",
    hero: "/art/velocity-run-hero.svg",
  },
  version: "1.2.0",
  supportedDevices: DEVICES,
  minPlayers: 1,
  maxPlayers: 4,
  sessionHint: "30–90 sec",
  sessionDuration: { minSec: 30, maxSec: 90 },
  modes: ["course-1", "course-2", "course-3"],
  scoreDirection: "lower",
  socialModes: SOCIAL,
  challengeTypes: TIME_CHALLENGE,
  ghostSupport: true,
  dailySupport: true,
  partySupport: true,
  leaderboards: ["global", "friends", "rivals"],
  howToPlay: [
    "Reach the beacon. Faster is better.",
    "Safe ledges sit low. Fast ledges sit high. Expert skips skip the stairs.",
    "Checkpoints print split deltas against your ghost. Death closes the attempt.",
    "R retries. 1/2/3 switch courses. G toggles ghost.",
  ],
  controls: [
    { input: "A D / ← →", action: "Move" },
    { input: "Space / ↑", action: "Jump" },
    { input: "S / ↓", action: "Fast fall" },
    { input: "1 2 3", action: "Switch course" },
    { input: "G", action: "Toggle ghost" },
    { input: "R", action: "Restart" },
  ],
  faq: [
    { q: "What are medals?", a: "Bronze, Silver, Gold, Platinum — first finishes land bronze/silver. Gold needs a line. Platinum is a clean ghost." },
    { q: "Do checkpoints save me?", a: "No. They print splits. A death closes the attempt so the clock stays honest." },
  ],
  achievements: [
    { key: "first-finish", name: "Beacon", description: "Finish any course.", xp: 15 },
    { key: "bronze", name: "Bronze Pulse", description: "Earn a bronze medal.", xp: 15 },
    { key: "gold", name: "Gold Line", description: "Earn a gold medal.", xp: 35 },
    { key: "platinum", name: "Author", description: "Earn a platinum medal.", xp: 70 },
    { key: "all-courses", name: "Three Gates", description: "Finish all three courses.", xp: 40 },
    { key: "no-death", name: "Clean Air", description: "Finish a course without dying.", xp: 30 },
    { key: "sub-40", name: "Rush", description: "Finish Course 1 under 40s.", xp: 25 },
    { key: "fast-fall", name: "Commit", description: "Use a fast fall mid-run.", xp: 10 },
    { key: "retry-10", name: "One More", description: "Retry a course 10 times in a session.", xp: 20 },
    { key: "pb-twice", name: "Split Hunter", description: "Beat a course PB twice.", xp: 30 },
  ],
};

export const swarmProtocolManifest: GameManifest = {
  id: "swarm-protocol",
  slug: "swarm-protocol",
  title: "Swarm Protocol",
  tagline: "Survive the protocol. Break the swarm.",
  description:
    "Compact arena survival. Auto-fire, readable silhouettes, and upgrades that rewrite the sixth minute.",
  genre: "Survival",
  tags: ["survival", "arena", "roguelite", "solo", "skill"],
  skills: ["positioning", "builds", "dash"],
  accent: "#f07a3a",
  accentSoft: "#2a140c",
  orientation: "landscape",
  inputMethods: ["keyboard", "mouse", "touch"],
  thumbnail: "/art/swarm-protocol-card.svg",
  hero: "/art/swarm-protocol-hero.svg",
  heroImage: "/art/swarm-protocol-hero.svg",
  tileImage: "/art/swarm-protocol-card.svg",
  backdropImage: "/art/swarm-protocol-hero.svg",
  media: {
    backdrop: "/art/swarm-protocol-hero.svg",
    tile: "/art/swarm-protocol-card.svg",
    hero: "/art/swarm-protocol-hero.svg",
  },
  version: "1.2.0",
  supportedDevices: DEVICES,
  minPlayers: 1,
  maxPlayers: 4,
  sessionHint: "6–8 min",
  sessionDuration: { minSec: 300, maxSec: 480 },
  modes: ["survival", "seed"],
  scoreDirection: "higher",
  socialModes: ["solo", "async-duel", "party", "daily"],
  challengeTypes: ["survive-seed", "survive-longer", "beat-build", "same-seed"],
  ghostSupport: false,
  dailySupport: true,
  partySupport: true,
  leaderboards: ["global", "friends", "rivals"],
  howToPlay: [
    "Move. The weapon tracks the nearest hostiles.",
    "Cores level you up. Pick one of three upgrades — builds rewrite the run.",
    "Dash has visible i-frames. Elite dashes telegraph. The Core arrives late.",
    "Defeating the Core is victory. Continue Endless is optional after the result.",
  ],
  controls: [
    { input: "WASD / arrows", action: "Move" },
    { input: "Shift", action: "Dash" },
    { input: "1 2 3", action: "Pick upgrade" },
    { input: "Esc", action: "Pause" },
    { input: "R", action: "Restart after death" },
  ],
  faq: [
    { q: "Is aiming required?", a: "Not at first. Auto-fire keeps the skill in positioning, dash timing, and builds." },
    { q: "How long is a run?", a: "Most runs resolve between five and eight minutes. The Core ends the run on kill." },
  ],
  achievements: [
    { key: "first-blood", name: "First Blood", description: "Defeat 10 hostiles.", xp: 10 },
    { key: "survive-2", name: "Warm Protocol", description: "Survive 2 minutes.", xp: 20 },
    { key: "survive-5", name: "Deep Protocol", description: "Survive 5 minutes.", xp: 40 },
    { key: "level-8", name: "Rewritten", description: "Reach player level 8 in a run.", xp: 35 },
    { key: "elite", name: "Marked", description: "Defeat an elite.", xp: 25 },
    { key: "splitter", name: "Division", description: "Defeat a splitter.", xp: 15 },
    { key: "dash-kill", name: "Through", description: "Defeat an enemy during dash i-frames.", xp: 20 },
    { key: "kills-200", name: "Clearance", description: "Defeat 200 hostiles in one run.", xp: 40 },
    { key: "shield", name: "Orbit", description: "Pick the orbiting shield.", xp: 15 },
    { key: "chain", name: "Cascade", description: "Pick chain.", xp: 15 },
  ],
};

export const skyStackManifest: GameManifest = {
  id: "sky-stack",
  slug: "sky-stack",
  title: "Sky Stack",
  tagline: "One tap. Perfect overlap. Keep climbing.",
  description:
    "Moving platforms, shrinking leftovers, fever streaks. A one-thumb high-score that asks for another try before the last piece even settles.",
  genre: "Arcade",
  tags: ["one-thumb", "high-score", "quick", "chill", "daily"],
  skills: ["timing", "precision"],
  accent: "#7ec8ff",
  accentSoft: "#142033",
  orientation: "portrait",
  inputMethods: ["keyboard", "mouse", "touch"],
  thumbnail: "/art/sky-stack-card.svg",
  hero: "/art/sky-stack-hero.svg",
  heroImage: "/art/sky-stack-hero.svg",
  tileImage: "/art/sky-stack-card.svg",
  backdropImage: "/art/sky-stack-hero.svg",
  media: {
    backdrop: "/art/sky-stack-hero.svg",
    tile: "/art/sky-stack-card.svg",
    hero: "/art/sky-stack-hero.svg",
  },
  version: "1.0.0",
  supportedDevices: DEVICES,
  minPlayers: 1,
  maxPlayers: 4,
  sessionHint: "20–90 sec",
  sessionDuration: { minSec: 20, maxSec: 90 },
  modes: ["climb", "daily"],
  scoreDirection: "higher",
  socialModes: SOCIAL,
  challengeTypes: SCORE_CHALLENGE,
  ghostSupport: false,
  dailySupport: true,
  partySupport: true,
  leaderboards: ["global", "friends", "rivals"],
  howToPlay: [
    "Tap, click, or press Space to place the moving slab.",
    "Perfect overlap keeps the width and feeds the streak.",
    "A miss ends the climb. Retry is instant.",
  ],
  controls: [
    { input: "Space / click / tap", action: "Place" },
    { input: "R", action: "Retry" },
  ],
  faq: [
    { q: "What is fever?", a: "A long perfect streak. Pitch rises, score multiplies, the sky warms." },
    { q: "Can I challenge a friend?", a: "Yes. Same seed, same first slabs. Beat their floor." },
  ],
  achievements: [
    { key: "first-place", name: "Placed", description: "Place your first slab.", xp: 10 },
    { key: "perfect-5", name: "Clean Five", description: "Land 5 perfects in a row.", xp: 25 },
    { key: "floor-30", name: "High Air", description: "Reach floor 30.", xp: 30 },
    { key: "fever", name: "Fever", description: "Enter fever mode.", xp: 20 },
    { key: "floor-67", name: "Sixty Seven", description: "Reach floor 67.", xp: 50 },
  ],
};

export const knockoutCircuitManifest: GameManifest = {
  id: "knockout-circuit",
  slug: "knockout-circuit",
  title: "Knockout Circuit",
  tagline: "Obstacles, shortcuts, recorded rivals.",
  description:
    "Three modular obstacle maps. Move, jump, dash. Ghosts replay as position markers so a solo run still feels like a race.",
  genre: "Obstacle",
  tags: ["obstacle", "race", "competitive", "skill", "async-multiplayer"],
  skills: ["jump", "dash", "routing"],
  accent: "#ffb703",
  accentSoft: "#2a1d08",
  orientation: "landscape",
  inputMethods: ["keyboard", "touch"],
  thumbnail: "/art/knockout-circuit-card.svg",
  hero: "/art/knockout-circuit-hero.svg",
  heroImage: "/art/knockout-circuit-hero.svg",
  tileImage: "/art/knockout-circuit-card.svg",
  backdropImage: "/art/knockout-circuit-hero.svg",
  media: {
    backdrop: "/art/knockout-circuit-hero.svg",
    tile: "/art/knockout-circuit-card.svg",
    hero: "/art/knockout-circuit-hero.svg",
  },
  version: "1.0.0",
  supportedDevices: DEVICES,
  minPlayers: 1,
  maxPlayers: 4,
  sessionHint: "45–120 sec",
  sessionDuration: { minSec: 45, maxSec: 120 },
  modes: ["map-a", "map-b", "map-c", "daily"],
  scoreDirection: "lower",
  socialModes: SOCIAL,
  challengeTypes: TIME_CHALLENGE,
  ghostSupport: true,
  dailySupport: true,
  partySupport: true,
  leaderboards: ["global", "friends", "rivals"],
  howToPlay: [
    "Reach the banner. Faster is better.",
    "Map A teaches the toys. Map B goes vertical. Map C pays for greed.",
    "Ghosts are recorded runs, not live players.",
  ],
  controls: [
    { input: "A D / ← →", action: "Move" },
    { input: "Space / ↑", action: "Jump" },
    { input: "Shift", action: "Dash" },
    { input: "1 2 3", action: "Switch map" },
    { input: "R", action: "Retry" },
  ],
  faq: [
    { q: "Are the other runners live?", a: "No. They are ghosts of recorded runs so the race still reads." },
  ],
  achievements: [
    { key: "first-gate", name: "Through", description: "Finish any map.", xp: 15 },
    { key: "all-maps", name: "Circuit", description: "Finish all three maps.", xp: 40 },
    { key: "no-hit", name: "Untouched", description: "Finish without a hazard hit.", xp: 30 },
    { key: "shortcut", name: "Greedy", description: "Take an expert shortcut.", xp: 20 },
  ],
};

export const pocketStrikerManifest: GameManifest = {
  id: "pocket-striker",
  slug: "pocket-striker",
  title: "Pocket Striker",
  tagline: "Aim. Power. Bank it in.",
  description:
    "Short physics arenas. Pull back to aim, release to strike, ride the cushions. Strokes are the sport — perfect for async 1v1.",
  genre: "Physics",
  tags: ["physics", "precision", "async-multiplayer", "chill", "quick"],
  skills: ["aim", "power", "banks"],
  accent: "#c4f1c2",
  accentSoft: "#142218",
  orientation: "either",
  inputMethods: ["keyboard", "mouse", "touch"],
  thumbnail: "/art/pocket-striker-card.svg",
  hero: "/art/pocket-striker-hero.svg",
  heroImage: "/art/pocket-striker-hero.svg",
  tileImage: "/art/pocket-striker-card.svg",
  backdropImage: "/art/pocket-striker-hero.svg",
  media: {
    backdrop: "/art/pocket-striker-hero.svg",
    tile: "/art/pocket-striker-card.svg",
    hero: "/art/pocket-striker-hero.svg",
  },
  version: "1.0.0",
  supportedDevices: DEVICES,
  minPlayers: 1,
  maxPlayers: 2,
  sessionHint: "30–90 sec",
  sessionDuration: { minSec: 30, maxSec: 90 },
  modes: ["layout", "daily"],
  scoreDirection: "lower",
  socialModes: ["solo", "async-duel", "party", "daily"],
  challengeTypes: ["beat-score", "same-seed"],
  ghostSupport: false,
  dailySupport: true,
  partySupport: true,
  leaderboards: ["global", "friends", "rivals"],
  howToPlay: [
    "Drag back from the striker to aim. Release to shoot.",
    "Fewer strokes win. Banks and perfects add bragging rights.",
    "12 layouts. Challenges lock the same table.",
  ],
  controls: [
    { input: "Drag / pointer", action: "Aim and power" },
    { input: "Release", action: "Strike" },
    { input: "R", action: "Retry" },
  ],
  faq: [
    { q: "What is a perfect?", a: "Hole-out in one stroke." },
    { q: "What is a bank?", a: "You hit a cushion, then the pocket, on that stroke." },
  ],
  achievements: [
    { key: "first-pocket", name: "Drop", description: "Pocket the striker once.", xp: 10 },
    { key: "perfect", name: "Ace", description: "Hole out in one stroke.", xp: 25 },
    { key: "bank", name: "Cushion", description: "Score a bank shot.", xp: 20 },
    { key: "par-table", name: "Table Manners", description: "Finish a layout at par or better.", xp: 25 },
  ],
};

export const territoryRushManifest: GameManifest = {
  id: "territory-rush",
  slug: "territory-rush",
  title: "Territory Rush",
  tagline: "Draw the loop. Take the floor.",
  description:
    "A 90-second geometric arena. Leave a trail, close it, claim the fill. Bots are seeded opponents with tells — never fake humans.",
  genre: "Arena",
  tags: ["arena", "area-control", "competitive", "async-multiplayer"],
  skills: ["space", "risk", "timing"],
  accent: "#ff4d6d",
  accentSoft: "#241018",
  orientation: "landscape",
  inputMethods: ["keyboard", "touch"],
  thumbnail: "/art/territory-rush-card.svg",
  hero: "/art/territory-rush-hero.svg",
  heroImage: "/art/territory-rush-hero.svg",
  tileImage: "/art/territory-rush-card.svg",
  backdropImage: "/art/territory-rush-hero.svg",
  media: {
    backdrop: "/art/territory-rush-hero.svg",
    tile: "/art/territory-rush-card.svg",
    hero: "/art/territory-rush-hero.svg",
  },
  version: "1.0.0",
  supportedDevices: DEVICES,
  minPlayers: 1,
  maxPlayers: 4,
  sessionHint: "~90 sec",
  sessionDuration: { minSec: 80, maxSec: 100 },
  modes: ["arena", "daily"],
  scoreDirection: "higher",
  socialModes: ["solo", "async-duel", "daily", "party"],
  challengeTypes: ["beat-score", "same-seed"],
  ghostSupport: false,
  dailySupport: true,
  partySupport: true,
  leaderboards: ["global", "friends", "rivals"],
  howToPlay: [
    "Move. Your trail is a claim in progress.",
    "Return to your color to fill the loop.",
    "Cut a bot trail to eliminate them. They can cut you too.",
  ],
  controls: [
    { input: "WASD / stick", action: "Move" },
    { input: "R", action: "Retry" },
  ],
  faq: [
    { q: "Are the others players?", a: "No. They are deterministic bots with names and styles, labeled as bots in metadata." },
  ],
  achievements: [
    { key: "first-claim", name: "Stake", description: "Capture your first loop.", xp: 10 },
    { key: "cut", name: "Shears", description: "Eliminate a bot by cutting its trail.", xp: 25 },
    { key: "half-map", name: "Majority", description: "Hold 50% of the arena.", xp: 40 },
  ],
};

export const crowdControlManifest: GameManifest = {
  id: "crowd-control",
  slug: "crowd-control",
  title: "Crowd Control",
  tagline: "Steer the pack. Pick the gate.",
  description:
    "A skill runner with a living count. Branch, time the gates, fight, and cash a finish multiplier. Ghosts remember which route they took.",
  genre: "Runner",
  tags: ["runner", "strategy", "skill", "one-thumb"],
  skills: ["routing", "timing", "risk"],
  accent: "#ff7a59",
  accentSoft: "#24140e",
  orientation: "either",
  inputMethods: ["keyboard", "touch"],
  thumbnail: "/art/crowd-control-card.svg",
  hero: "/art/crowd-control-hero.svg",
  heroImage: "/art/crowd-control-hero.svg",
  tileImage: "/art/crowd-control-card.svg",
  backdropImage: "/art/crowd-control-hero.svg",
  media: {
    backdrop: "/art/crowd-control-hero.svg",
    tile: "/art/crowd-control-card.svg",
    hero: "/art/crowd-control-hero.svg",
  },
  version: "1.0.0",
  supportedDevices: DEVICES,
  minPlayers: 1,
  maxPlayers: 4,
  sessionHint: "45–75 sec",
  sessionDuration: { minSec: 45, maxSec: 75 },
  modes: ["rush", "daily"],
  scoreDirection: "higher",
  socialModes: SOCIAL,
  challengeTypes: ["beat-score", "beat-route", "same-seed"],
  ghostSupport: true,
  dailySupport: true,
  partySupport: true,
  leaderboards: ["global", "friends", "rivals"],
  howToPlay: [
    "The pack runs forward. You steer.",
    "Gates add, multiply, or tax the crowd.",
    "Hidden left routes can be faster. Right routes can be richer.",
  ],
  controls: [
    { input: "A D / drag", action: "Steer" },
    { input: "Shift", action: "Dash" },
    { input: "R", action: "Retry" },
  ],
  faq: [
    { q: "Is it auto-run?", a: "Forward motion is automatic. Everything that matters — lane, gate, fight, dash — is on you." },
  ],
  achievements: [
    { key: "first-gate", name: "Through the gate", description: "Take your first gate.", xp: 10 },
    { key: "x4", name: "Crowd Surge", description: "Hit a x4 multiplier.", xp: 25 },
    { key: "shortcut", name: "Cut In", description: "Take a hidden shortcut.", xp: 20 },
    { key: "finish-80", name: "Parade", description: "Finish with 80 or more in the pack.", xp: 35 },
  ],
};

export const GAME_MANIFESTS: GameManifest[] = [
  neonDriftManifest,
  velocityRunManifest,
  swarmProtocolManifest,
  skyStackManifest,
  knockoutCircuitManifest,
  pocketStrikerManifest,
  territoryRushManifest,
  crowdControlManifest,
];

export const PLATFORM_ACHIEVEMENTS = platformAchievements;

export function getManifest(slug: string): GameManifest | undefined {
  return GAME_MANIFESTS.find((game) => game.slug === slug || game.id === slug);
}

export function allAchievements(): Array<AchievementDefinition & { gameId: string | null }> {
  const list: Array<AchievementDefinition & { gameId: string | null }> = platformAchievements.map(
    (a) => ({ ...a, gameId: null }),
  );
  for (const game of GAME_MANIFESTS) {
    for (const a of game.achievements) list.push({ ...a, gameId: game.id });
  }
  return list;
}
